# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('country', models.CharField(choices=[('gr', 'Greece'), ('rm', 'Romania'), ('bg', 'Bulgaria'), ('it', 'Italy')], max_length=2)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('tk', models.PositiveIntegerField(blank=True, null=True, verbose_name='Postcode')),
                ('max_evacuation_time', models.PositiveIntegerField(blank=True, default=0, help_text='in seconds', null=True, verbose_name='Maximum Evacuation Time')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
