# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['-updated']},
        ),
        migrations.AddField(
            model_name='building',
            name='photo',
            field=models.ImageField(blank=True, help_text='Supported Formats: png, jpg, jpeg, bmp', null=True, upload_to='building_images/'),
        ),
    ]
