# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_auto_20160511_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('number', models.SmallIntegerField(verbose_name='Floor Level')),
                ('blueprint', models.ImageField(upload_to='blueprints/')),
                ('max_evacuation_time', models.PositiveIntegerField(blank=True, default=0, help_text='in seconds', null=True, verbose_name='Maximum Evacuation Time')),
                ('stud_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of students')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Building')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
