# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='blueprint',
            field=models.ImageField(blank=True, null=True, upload_to='blueprints/'),
        ),
    ]
